apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cli-plugin-template
  description: Template containing all the essential boilerplates to help you
    create new Toolbelt plugins
  tags:
    - typescript
    - oclif
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex/cli-plugin-template
    backstage.io/techdocs-ref: dir:../
spec:
  lifecycle: stable
  owner: apps
  type: template
  dependsOn:
    - component:toolbelt
